name: Lint and Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install ESLint
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        env:
          GITHUB_PUBLIC_ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npm run test
