name: Lint and Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install ESLint
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        env:
          GITHUB_PUBLIC_ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_CV_REPO_OWNER: ${{secrets.CV_REPO_OWNER}}
          GITHUB_CV_REPO_NAME: ${{secrets.CV_REPO_NAME}}
          GITHUB_CV_ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CV_FILE: ${{secrets.CV_FILE}}
          BIB_FILE: ${{secrets.BIB_FILE}}
        run: npm run test
