name: Package tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]
        package: ["latex-to-html", "markdown-to-html"]

    defaults:
      run:
        working-directory: ./packages/${{matrix.package}}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Setup pnpm
      run: npm install -g pnpm@latest

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test
