name: Package tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["latex-to-html", "markdown-to-html", "html-processor"]

    defaults:
      run:
        working-directory: ./packages/${{matrix.package}}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
